<?php require __DIR__.'/assessment/backend.php'; ?>
<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Free clinic assessment | My Physio Saathi</title><meta name="description" content="Complete 25 questions about your clinic's daily processes and receive a self-reported clinic workflow report as a PDF."><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="assessment/form.css"></head><body>
<a class="skip" href="#main">Skip to assessment</a><header><div class="container header-inner"><a href="index.html" class="brand">My Physio <span class="brand-saathi">Saathi</span><span class="brand-category">Physiotherapy Clinic Software</span></a><a class="button small" href="tel:+919825647083">Call Tejas</a></div></header>
<main id="main"><section class="assessment-intro"><div class="container"><p class="eyebrow">Free clinic workflow audit · Step 1</p><h1>How reliably does your<br><span>clinic's day run?</span></h1><p class="assessment-lead">Review patient records, treatment notes, payments, staff coordination and information protection. A reliable paper-based process can score well, just as a reliable digital process can.</p><div class="assessment-facts"><span>25 questions</span><span>5 domains</span><span>Your submitted answers by email</span></div></div></section>
<div class="container assessment-body">
<?php if($receipt): ?>
<section class="assessment-success" role="status"><p class="eyebrow">Assessment submitted</p><h2>Your clinic workflow report has been sent.</h2><p>Copies have been sent to <?=esc($receipt['email'])?> and the My Physio Saathi team. Check your inbox and spam folder.</p><p class="reference">Reference: <?=esc($receipt['id'])?></p><a class="button" href="index.html">Explore My Physio Saathi</a></section>
<?php else: ?>
<?php if(!$ready): ?><div class="setup-notice" role="status"><strong>Email delivery is being configured.</strong> Submission is unavailable until delivery is tested. You can review the questions below or <a href="tel:+919825647083">call Tejas</a>.</div><?php endif; ?>
<?php if($errors): ?><div class="validation-summary" role="alert" tabindex="-1" id="error-summary"><h2>Please check your assessment</h2><ul><?php foreach($errors as $key=>$error): ?><li><?php if($key!=='form'): ?><a href="#<?=$key==='beds'?'beds':esc($key)?>"><?=esc($error)?></a><?php else: ?><?=esc($error)?><?php endif; ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<section class="rating-guide" aria-labelledby="rating-heading"><div><p class="eyebrow">About this assessment</p><h2 id="rating-heading">Rate your current practice.</h2><p>Use your experience over the last 30 days. For occasional activities, use the most recent evidence. Choose one answer for every question. “Not sure” and “N/A” are separate responses, not numeric scores.</p></div><dl><div><dt>1 · Very low</dt><dd>No reliable process exists, or this almost never happens.</dd></div><div><dt>2 · Low</dt><dd>This happens occasionally and depends heavily on individual effort.</dd></div><div><dt>3 · Moderate</dt><dd>A process exists, but there are frequent gaps or inconsistencies.</dd></div><div><dt>4 · High</dt><dd>This works reliably in most cases, with occasional exceptions.</dd></div><div><dt>5 · Very high</dt><dd>This works consistently and can be demonstrated with recent examples.</dd></div></dl></section>
<form method="post" action="free-assesment.php" id="assessment-form">
<input type="hidden" name="csrf" value="<?=esc($_SESSION['token'])?>">
<div class="honeypot" aria-hidden="true"><label for="website">Leave blank</label><input id="website" name="website" tabindex="-1" autocomplete="off"></div>
<section class="profile-section" aria-labelledby="profile-title"><div class="assessment-section-heading"><p class="eyebrow">Section 1 · Clinic profile</p><h2 id="profile-title">Tell us about your clinic.</h2><p>All clinic details are required. Do not enter patient details or medical information.</p></div><div class="profile-grid">
<?php foreach($labels as $key=>$label): $type=$key==='email'?'email':($key==='mobile'?'tel':($key==='beds'?'number':'text')); ?>
<div class="field <?=$key==='location'?'wide':''?>"><label for="<?=esc($key)?>"><?=esc($label)?> <span aria-hidden="true">*</span></label><input type="<?=$type?>" id="<?=esc($key)?>" name="<?=esc($key)?>" value="<?=esc($values[$key])?>" required <?=($key==='beds'?'min="0" max="9999" step="1"':'maxlength="'.($key==='location'?500:($key==='email'?254:160)).'"')?> autocomplete="<?=esc(['doctor_name'=>'name','email'=>'email','mobile'=>'tel','clinic_name'=>'organization','location'=>'street-address','city'=>'address-level2'][$key]??'off')?>" <?=isset($errors[$key])?'aria-invalid="true"':''?> aria-describedby="<?=esc($key)?>-help <?=esc($key)?>-error"><small id="<?=esc($key)?>-help"><?php if($key==='beds'): ?>Enter 0 if your clinic has no beds or treatment couches.<?php elseif($key==='email'): ?>We will email your completed PDF to this address.<?php elseif($key==='mobile'): ?>Indian mobile number, with or without +91.<?php endif; ?></small><span class="field-error" id="<?=esc($key)?>-error"><?=esc($errors[$key]??'')?></span></div>
<?php endforeach; ?></div></section>
<div class="assessment-progress"><span><strong id="answered-count">0</strong> of 25 questions answered</span><a href="#assessment-submit">Go to submit</a></div>
<?php foreach($domains as $domain): ?>
<section class="domain-section" aria-labelledby="domain-<?=esc($domain['code'])?>"><div class="assessment-section-heading"><p class="eyebrow">Domain <?=esc($domain['code'])?> · 5 required questions</p><h2 id="domain-<?=esc($domain['code'])?>"><?=esc($domain['title'])?></h2><p><?=esc($domain['description'])?></p></div>
<?php foreach($domain['questions'] as $id=>$question): ?>
<fieldset class="question-card <?=isset($errors[$id])?'has-error':''?>" id="<?=esc($id)?>" aria-describedby="<?=esc($id)?>-error"><legend><span class="question-id"><?=esc($id)?></span><?=esc($question)?> <span class="required-word">(required)</span></legend><div class="rating-options">
<?php foreach($ratings as $value=>$label): ?><label class="rating-option"><input type="radio" name="answers[<?=esc($id)?>]" value="<?=esc($value)?>" required <?=(string)($answers[$id]??'')===(string)$value?'checked':''?>><span><?=esc($label)?></span></label><?php endforeach; ?>
</div><p class="field-error" id="<?=esc($id)?>-error"><?=esc($errors[$id]??'')?></p><label class="notes-label" for="note-<?=esc($id)?>">Notes <span>(optional)</span></label><textarea id="note-<?=esc($id)?>" name="notes[<?=esc($id)?>]" rows="2" maxlength="600"><?=esc($notes[$id]??'')?></textarea></fieldset>
<?php endforeach; ?></section><?php endforeach; ?>
<section class="assessment-submit" id="assessment-submit"><div><p class="eyebrow">Your completed assessment</p><h2>Get your clinic workflow report.</h2><p>A copy will be emailed to you and the My Physio Saathi team. Your report includes your answers, score coverage, practical recommendations, suggested measures and a 90-day improvement roadmap. It is not a verified audit.</p><p class="privacy">We use your clinic and contact details to prepare and email your report and respond to your enquiry. Answers and reports are stored privately to reproduce your report and retry delivery. Do not include patient names, reports or medical information.</p></div><div class="submit-actions"><button class="button" type="submit" id="assessment-button" <?=$ready?'':'disabled'?>><?=isset($_SESSION['pending_reference'])?'Retry report delivery':'Submit and email my PDF'?></button><p>Tejas P Mehta<br><a href="tel:+919825647083">Call: +91 98256 47083</a></p><p id="sending-status" role="status" hidden>Creating your PDF and sending copies. Please keep this page open.</p></div></section></form>
<?php endif; ?></div></main>
<footer><div class="container footer-inner"><p>My Physio Saathi<br><span>Every patient visit, connected.</span></p><p>Tejas P Mehta<br><a href="tel:+919825647083">Call: +91 98256 47083</a></p><a href="#main">Back to top</a></div></footer><script src="assessment/form.js" defer></script></body></html>
