<?php
// Version this catalogue whenever wording or recommendations change.
$catalogue = [
 'version'=>'1.1.0',
 // Empty until capabilities are separately verified and approved. Never list reminders,
 // automatic reconciliation, backups or recovery testing without separate verification.
 'verified_capability_allowlist'=>[],
 'questions'=>[
 'A1'=>[
  'id'=>'A1',
  'domain'=>'A',
  'title'=>'One patient identifier',
  'consequence'=>'Duplicate or fragmented records may make earlier information harder to find.',
  'recommendations'=>[1=>'Assign one patient identifier and check duplicate records. Establish a simple written process and try it with a small sample.', 2=>'Assign one patient identifier and check duplicate records. Agree consistent steps and check that staff follow them.', 3=>'Assign one patient identifier and check duplicate records. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Assign one patient identifier and check duplicate records. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Check a sample of repeat patients for a single identifier and resolve duplicate records.',
  'role'=>'Receptionist and clinic owner',
  'timing'=>'Within 7 days',
  'completion_check'=>'Check a sample of repeat patients for a single identifier and resolve duplicate records.',
 ],
 'A2'=>[
  'id'=>'A2',
  'domain'=>'A',
  'title'=>'Complete registration details',
  'consequence'=>'Missing registration details may cause repeated questions or difficulty contacting the patient.',
  'recommendations'=>[1=>'Use a registration completeness checklist. Establish a simple written process and try it with a small sample.', 2=>'Use a registration completeness checklist. Agree consistent steps and check that staff follow them.', 3=>'Use a registration completeness checklist. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Use a registration completeness checklist. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Review a sample of new registrations against the agreed checklist.',
  'role'=>'Receptionist',
  'timing'=>'Within 7 days',
  'completion_check'=>'Review a sample of new registrations against the agreed checklist.',
 ],
 'A3'=>[
  'id'=>'A3',
  'domain'=>'A',
  'title'=>'Find patient records consistently',
  'consequence'=>'Records that are difficult to locate may interrupt repeat visits.',
  'recommendations'=>[1=>'Standardise record indexing and test retrieval time. Establish a simple written process and try it with a small sample.', 2=>'Standardise record indexing and test retrieval time. Agree consistent steps and check that staff follow them.', 3=>'Standardise record indexing and test retrieval time. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Standardise record indexing and test retrieval time. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Ask a backup staff member to retrieve a sample of records and record the time taken.',
  'role'=>'Receptionist and therapist',
  'timing'=>'Within 14 days',
  'completion_check'=>'Ask a backup staff member to retrieve a sample of records and record the time taken.',
 ],
 'A4'=>[
  'id'=>'A4',
  'domain'=>'A',
  'title'=>'Link reports to the correct patient',
  'consequence'=>'Unclear report labels may cause confusion when reviewing patient information.',
  'recommendations'=>[1=>'Link and label medical reports against the correct patient. Establish a simple written process and try it with a small sample.', 2=>'Link and label medical reports against the correct patient. Agree consistent steps and check that staff follow them.', 3=>'Link and label medical reports against the correct patient. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Link and label medical reports against the correct patient. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Check a sample of report files for the correct patient identifier and clear labels.',
  'role'=>'Therapist and receptionist',
  'timing'=>'Within 7 days',
  'completion_check'=>'Check a sample of report files for the correct patient identifier and clear labels.',
 ],
 'A5'=>[
  'id'=>'A5',
  'domain'=>'A',
  'title'=>'Keep existing information current',
  'consequence'=>'Outdated or inaccessible information may lead to repeated collection of details.',
  'recommendations'=>[1=>'Keep existing information accessible and current. Establish a simple written process and try it with a small sample.', 2=>'Keep existing information accessible and current. Agree consistent steps and check that staff follow them.', 3=>'Keep existing information accessible and current. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Keep existing information accessible and current. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Review repeat-patient records for accessible history and current information.',
  'role'=>'Therapist',
  'timing'=>'Within 14 days',
  'completion_check'=>'Review repeat-patient records for accessible history and current information.',
 ],
 'B1'=>[
  'id'=>'B1',
  'domain'=>'B',
  'title'=>'Consistent initial assessment',
  'consequence'=>'Inconsistent initial records may make the treatment episode harder to understand.',
  'recommendations'=>[1=>'Use a consistent initial-assessment template. Establish a simple written process and try it with a small sample.', 2=>'Use a consistent initial-assessment template. Agree consistent steps and check that staff follow them.', 3=>'Use a consistent initial-assessment template. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Use a consistent initial-assessment template. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Check a sample of new episodes for the agreed initial-assessment fields.',
  'role'=>'Lead therapist',
  'timing'=>'Within 14 days',
  'completion_check'=>'Check a sample of new episodes for the agreed initial-assessment fields.',
 ],
 'B2'=>[
  'id'=>'B2',
  'domain'=>'B',
  'title'=>'Clear treatment goals',
  'consequence'=>'An unclear goal may make it difficult for staff to understand the intended plan.',
  'recommendations'=>[1=>'Record a clear treatment goal for each episode. Establish a simple written process and try it with a small sample.', 2=>'Record a clear treatment goal for each episode. Agree consistent steps and check that staff follow them.', 3=>'Record a clear treatment goal for each episode. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Record a clear treatment goal for each episode. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Check that each sampled episode contains a clear recorded goal.',
  'role'=>'Treating therapist',
  'timing'=>'Within 7 days',
  'completion_check'=>'Check that each sampled episode contains a clear recorded goal.',
 ],
 'B3'=>[
  'id'=>'B3',
  'domain'=>'B',
  'title'=>'Dated notes on the treatment day',
  'consequence'=>'Delayed notes may make visit details harder to recall accurately.',
  'recommendations'=>[1=>'Complete dated notes on the treatment day. Establish a simple written process and try it with a small sample.', 2=>'Complete dated notes on the treatment day. Agree consistent steps and check that staff follow them.', 3=>'Complete dated notes on the treatment day. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Complete dated notes on the treatment day. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Check a sample of completed visits for dated notes completed on the treatment day.',
  'role'=>'Treating therapist',
  'timing'=>'Within 7 days',
  'completion_check'=>'Check a sample of completed visits for dated notes completed on the treatment day.',
 ],
 'B4'=>[
  'id'=>'B4',
  'domain'=>'B',
  'title'=>'Useful treatment activity detail',
  'consequence'=>'Missing activity detail may make repeat visits or therapist handovers harder.',
  'recommendations'=>[1=>'Standardise the detail recorded for exercises and treatment activities. Establish a simple written process and try it with a small sample.', 2=>'Standardise the detail recorded for exercises and treatment activities. Agree consistent steps and check that staff follow them.', 3=>'Standardise the detail recorded for exercises and treatment activities. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Standardise the detail recorded for exercises and treatment activities. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Check sample session notes for exercise or activity names, relevant duration and remarks.',
  'role'=>'Lead therapist',
  'timing'=>'Within 14 days',
  'completion_check'=>'Check sample session notes for exercise or activity names, relevant duration and remarks.',
 ],
 'B5'=>[
  'id'=>'B5',
  'domain'=>'B',
  'title'=>'Understandable therapist handovers',
  'consequence'=>'A plan that relies on verbal explanation may limit continuity when staff change.',
  'recommendations'=>[1=>'Test whether another therapist can understand the plan from the record. Establish a simple written process and try it with a small sample.', 2=>'Test whether another therapist can understand the plan from the record. Agree consistent steps and check that staff follow them.', 3=>'Test whether another therapist can understand the plan from the record. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Test whether another therapist can understand the plan from the record. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Ask another therapist to explain the recorded plan without a verbal briefing.',
  'role'=>'Lead therapist and another therapist',
  'timing'=>'Within 14 days',
  'completion_check'=>'Ask another therapist to explain the recorded plan without a verbal briefing.',
 ],
 'C1'=>[
  'id'=>'C1',
  'domain'=>'C',
  'title'=>'Record chargeable sessions',
  'consequence'=>'Unrecorded charges may leave the patient ledger incomplete.',
  'recommendations'=>[1=>'Compare chargeable sessions against recorded charges. Establish a simple written process and try it with a small sample.', 2=>'Compare chargeable sessions against recorded charges. Agree consistent steps and check that staff follow them.', 3=>'Compare chargeable sessions against recorded charges. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Compare chargeable sessions against recorded charges. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Compare a sample of chargeable sessions with the corresponding recorded charges.',
  'role'=>'Receptionist and clinic owner',
  'timing'=>'Within 7 days',
  'completion_check'=>'Compare a sample of chargeable sessions with the corresponding recorded charges.',
 ],
 'C2'=>[
  'id'=>'C2',
  'domain'=>'C',
  'title'=>'Record payments promptly',
  'consequence'=>'Delayed or incorrectly assigned payments may leave balances unclear.',
  'recommendations'=>[1=>'Record payments against the correct patient on the same day. Establish a simple written process and try it with a small sample.', 2=>'Record payments against the correct patient on the same day. Agree consistent steps and check that staff follow them.', 3=>'Record payments against the correct patient on the same day. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Record payments against the correct patient on the same day. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Match a sample of receipts to the correct patient and payment date.',
  'role'=>'Receptionist',
  'timing'=>'Within 7 days',
  'completion_check'=>'Match a sample of receipts to the correct patient and payment date.',
 ],
 'C3'=>[
  'id'=>'C3',
  'domain'=>'C',
  'title'=>'One clear patient ledger',
  'consequence'=>'Separate payment records may make outstanding balances harder to determine.',
  'recommendations'=>[1=>'Maintain one patient ledger showing the outstanding balance. Establish a simple written process and try it with a small sample.', 2=>'Maintain one patient ledger showing the outstanding balance. Agree consistent steps and check that staff follow them.', 3=>'Maintain one patient ledger showing the outstanding balance. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Maintain one patient ledger showing the outstanding balance. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Check sample patient ledgers against charges and payments to confirm the displayed balance.',
  'role'=>'Receptionist',
  'timing'=>'Within 14 days',
  'completion_check'=>'Check sample patient ledgers against charges and payments to confirm the displayed balance.',
 ],
 'C4'=>[
  'id'=>'C4',
  'domain'=>'C',
  'title'=>'Check recorded collections',
  'consequence'=>'Differences between recorded payments and actual collections may remain unnoticed.',
  'recommendations'=>[1=>'Reconcile recorded payments against actual collections. Establish a simple written process and try it with a small sample.', 2=>'Reconcile recorded payments against actual collections. Agree consistent steps and check that staff follow them.', 3=>'Reconcile recorded payments against actual collections. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Reconcile recorded payments against actual collections. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Document a comparison of recorded payments with actual collections and resolve differences.',
  'role'=>'Clinic owner or nominated accounts person',
  'timing'=>'Within 7 days',
  'completion_check'=>'Document a comparison of recorded payments with actual collections and resolve differences.',
 ],
 'C5'=>[
  'id'=>'C5',
  'domain'=>'C',
  'title'=>'Review overdue balances routinely',
  'consequence'=>'Balances that are not reviewed may remain unresolved.',
  'recommendations'=>[1=>'Assign a routine overdue-balance review. Establish a simple written process and try it with a small sample.', 2=>'Assign a routine overdue-balance review. Agree consistent steps and check that staff follow them.', 3=>'Assign a routine overdue-balance review. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Assign a routine overdue-balance review. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Maintain a dated review list with a responsible person and next step for each overdue balance.',
  'role'=>'Receptionist and clinic owner',
  'timing'=>'Within 7 days',
  'completion_check'=>'Maintain a dated review list with a responsible person and next step for each overdue balance.',
 ],
 'D1'=>[
  'id'=>'D1',
  'domain'=>'D',
  'title'=>'Responsibility for record completion',
  'consequence'=>'Unclear responsibility may leave parts of the record unfinished.',
  'recommendations'=>[1=>'Assign clear responsibility for patient-record completion. Establish a simple written process and try it with a small sample.', 2=>'Assign clear responsibility for patient-record completion. Agree consistent steps and check that staff follow them.', 3=>'Assign clear responsibility for patient-record completion. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Assign clear responsibility for patient-record completion. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Write down who completes and checks each part of a patient record.',
  'role'=>'Clinic owner',
  'timing'=>'Within 7 days',
  'completion_check'=>'Write down who completes and checks each part of a patient record.',
 ],
 'D2'=>[
  'id'=>'D2',
  'domain'=>'D',
  'title'=>'Backup for routine administration',
  'consequence'=>'Routine work may be interrupted when the usual staff member is absent.',
  'recommendations'=>[1=>'Document routine administration and train a backup person. Establish a simple written process and try it with a small sample.', 2=>'Document routine administration and train a backup person. Agree consistent steps and check that staff follow them.', 3=>'Document routine administration and train a backup person. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Document routine administration and train a backup person. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Have a backup person complete a sample routine task using the written steps.',
  'role'=>'Receptionist and nominated backup',
  'timing'=>'Within 14 days',
  'completion_check'=>'Have a backup person complete a sample routine task using the written steps.',
 ],
 'D3'=>[
  'id'=>'D3',
  'domain'=>'D',
  'title'=>'Review unexpected discontinuation',
  'consequence'=>'Unexpected discontinuation may go unnoticed without a regular review.',
  'recommendations'=>[1=>'Maintain a review list for unexpected treatment discontinuation. Establish a simple written process and try it with a small sample.', 2=>'Maintain a review list for unexpected treatment discontinuation. Agree consistent steps and check that staff follow them.', 3=>'Maintain a review list for unexpected treatment discontinuation. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Maintain a review list for unexpected treatment discontinuation. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Review a list of unexpectedly discontinued episodes and document the next step where appropriate.',
  'role'=>'Lead therapist',
  'timing'=>'Within 14 days',
  'completion_check'=>'Review a list of unexpectedly discontinued episodes and document the next step where appropriate.',
 ],
 'D4'=>[
  'id'=>'D4',
  'domain'=>'D',
  'title'=>'Accurate weekly session summary',
  'consequence'=>'An incomplete summary may make clinic activity harder to review.',
  'recommendations'=>[1=>'Establish an accurate weekly completed-session summary. Establish a simple written process and try it with a small sample.', 2=>'Establish an accurate weekly completed-session summary. Agree consistent steps and check that staff follow them.', 3=>'Establish an accurate weekly completed-session summary. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Establish an accurate weekly completed-session summary. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Compare one weekly summary with the underlying completed-session records.',
  'role'=>'Receptionist and clinic owner',
  'timing'=>'Within 14 days',
  'completion_check'=>'Compare one weekly summary with the underlying completed-session records.',
 ],
 'D5'=>[
  'id'=>'D5',
  'domain'=>'D',
  'title'=>'Routine owner review',
  'consequence'=>'Recurring process issues may remain open without an owner review.',
  'recommendations'=>[1=>'Schedule a routine owner review and track corrective actions. Establish a simple written process and try it with a small sample.', 2=>'Schedule a routine owner review and track corrective actions. Agree consistent steps and check that staff follow them.', 3=>'Schedule a routine owner review and track corrective actions. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Schedule a routine owner review and track corrective actions. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Record a review date, the issues considered and a responsible person for each agreed action.',
  'role'=>'Clinic owner',
  'timing'=>'Within 30 days',
  'completion_check'=>'Record a review date, the issues considered and a responsible person for each agreed action.',
 ],
 'E1'=>[
  'id'=>'E1',
  'domain'=>'E',
  'title'=>'Access according to responsibilities',
  'consequence'=>'Unnecessary access may expose records beyond staff responsibilities.',
  'recommendations'=>[1=>'Review access according to staff responsibilities. Establish a simple written process and try it with a small sample.', 2=>'Review access according to staff responsibilities. Agree consistent steps and check that staff follow them.', 3=>'Review access according to staff responsibilities. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Review access according to staff responsibilities. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Review current users and confirm that each has only the access required for their role.',
  'role'=>'Clinic owner',
  'timing'=>'Within 7 days',
  'completion_check'=>'Review current users and confirm that each has only the access required for their role.',
 ],
 'E2'=>[
  'id'=>'E2',
  'domain'=>'E',
  'title'=>'Protect records from public viewing',
  'consequence'=>'Visible files or screens may expose patient information to visitors.',
  'recommendations'=>[1=>'Protect records from public viewing. Establish a simple written process and try it with a small sample.', 2=>'Protect records from public viewing. Agree consistent steps and check that staff follow them.', 3=>'Protect records from public viewing. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Protect records from public viewing. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Walk through reception and treatment areas and check files, screens and storage for public visibility.',
  'role'=>'Clinic owner and all staff',
  'timing'=>'Within 7 days',
  'completion_check'=>'Walk through reception and treatment areas and check files, screens and storage for public visibility.',
 ],
 'E3'=>[
  'id'=>'E3',
  'domain'=>'E',
  'title'=>'Protected recovery copy',
  'consequence'=>'Without a separate recovery copy, records may be unavailable after a loss or failure.',
  'recommendations'=>[1=>'Maintain a separate, protected recovery copy. Establish a simple written process and try it with a small sample.', 2=>'Maintain a separate, protected recovery copy. Agree consistent steps and check that staff follow them.', 3=>'Maintain a separate, protected recovery copy. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Maintain a separate, protected recovery copy. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Confirm where the separate copy is held, who can access it and how current it is.',
  'role'=>'Clinic owner and hosting or IT provider',
  'timing'=>'Within 7 days',
  'completion_check'=>'Confirm where the separate copy is held, who can access it and how current it is.',
 ],
 'E4'=>[
  'id'=>'E4',
  'domain'=>'E',
  'title'=>'Document a recovery test',
  'consequence'=>'An untested recovery arrangement may not restore usable records when needed.',
  'recommendations'=>[1=>'Perform and document a recovery test. Establish a simple written process and try it with a small sample.', 2=>'Perform and document a recovery test. Agree consistent steps and check that staff follow them.', 3=>'Perform and document a recovery test. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Perform and document a recovery test. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Restore a safe test copy and document the date, result and any corrective action.',
  'role'=>'Clinic owner and hosting or IT provider',
  'timing'=>'Within 14 days',
  'completion_check'=>'Restore a safe test copy and document the date, result and any corrective action.',
 ],
 'E5'=>[
  'id'=>'E5',
  'domain'=>'E',
  'title'=>'Remove access when staff leave',
  'consequence'=>'Departed staff may retain access if removal is not checked.',
  'recommendations'=>[1=>'Use a staff-exit checklist to remove access promptly. Establish a simple written process and try it with a small sample.', 2=>'Use a staff-exit checklist to remove access promptly. Agree consistent steps and check that staff follow them.', 3=>'Use a staff-exit checklist to remove access promptly. Review a sample regularly and address inconsistent entries.'],
  'maintenance'=>'Use a staff-exit checklist to remove access promptly. Keep the process under periodic review; this response has not been independently verified.',
  'verification'=>'Ask the responsible person to describe the current process and show a recent example. Review recent staff exits and document removal of accounts, keys and shared access where relevant.',
  'role'=>'Clinic owner',
  'timing'=>'Within 7 days',
  'completion_check'=>'Review recent staff exits and document removal of accounts, keys and shared access where relevant.',
 ],
 ],
];

// Snapshot the complete measurement catalogue with each report.
$catalogue['measurement_catalogue']=require __DIR__.'/roadmap-catalogue.php';
return $catalogue;
