<?php
// One active revised assessment. Bump this version when question-specific mappings change.
$catalogue = ['version'=>'2.0.0','verified_capability_allowlist'=>[], 'questions'=>[
'A1'=>[
'id'=>'A1',
'domain'=>'A',
'question'=>'How reliably can you find a returning patient\'s complete file within two minutes, even when the person who normally handles files is absent?',
'title'=>'Find files with absence cover',
'consequence'=>'Files that depend on one person may be harder to find during their absence.',
'role'=>'Receptionist and nominated backup',
'timing'=>'Within 14 days',
'completion_check'=>'Time a sample of five anonymised retrieval attempts.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Time a sample of five anonymised retrieval attempts.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Standardise filing and train a backup person to retrieve records. Establish the routine and identify who will carry it out.', 2=>'Standardise filing and train a backup person to retrieve records. Make the steps consistent and assign responsibility.', 3=>'Standardise filing and train a backup person to retrieve records. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Time a sample of five anonymised retrieval attempts.', 5=>'Recognise this as a reported strength and maintain periodic review. Time a sample of five anonymised retrieval attempts.'],
],
'A2'=>[
'id'=>'A2',
'domain'=>'A',
'question'=>'How consistently do you check that a new patient\'s required details are complete before the first treatment begins?',
'title'=>'Check registration completeness',
'consequence'=>'Missing required details may lead to repeated questions before treatment.',
'role'=>'Receptionist',
'timing'=>'Within 7 days',
'completion_check'=>'Review a sample of new registrations for missing required details.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Review a sample of new registrations for missing required details.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Use a registration checklist and assign the completeness check. Establish the routine and identify who will carry it out.', 2=>'Use a registration checklist and assign the completeness check. Make the steps consistent and assign responsibility.', 3=>'Use a registration checklist and assign the completeness check. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Review a sample of new registrations for missing required details.', 5=>'Recognise this as a reported strength and maintain periodic review. Review a sample of new registrations for missing required details.'],
],
'A3'=>[
'id'=>'A3',
'domain'=>'A',
'question'=>'How consistently do you check for an existing patient file before creating a new one?',
'title'=>'Check before creating another file',
'consequence'=>'Duplicate files may separate information about the same patient.',
'role'=>'Receptionist',
'timing'=>'Within 14 days',
'completion_check'=>'Review new files for duplicate patient records.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Review new files for duplicate patient records.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Search existing records using agreed identifying details before opening a file. Establish the routine and identify who will carry it out.', 2=>'Search existing records using agreed identifying details before opening a file. Make the steps consistent and assign responsibility.', 3=>'Search existing records using agreed identifying details before opening a file. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Review new files for duplicate patient records.', 5=>'Recognise this as a reported strength and maintain periodic review. Review new files for duplicate patient records.'],
],
'A4'=>[
'id'=>'A4',
'domain'=>'A',
'question'=>'How reliably can the treating doctor find the patient\'s latest medical report without searching through separate messages or loose papers?',
'title'=>'Find the latest medical report',
'consequence'=>'Separate messages or loose papers may make the latest report harder to locate.',
'role'=>'Treating doctor and receptionist',
'timing'=>'Within 14 days',
'completion_check'=>'Check that the latest relevant report can be found in sampled records.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Check that the latest relevant report can be found in sampled records.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Keep dated medical reports with the correct patient record. Establish the routine and identify who will carry it out.', 2=>'Keep dated medical reports with the correct patient record. Make the steps consistent and assign responsibility.', 3=>'Keep dated medical reports with the correct patient record. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Check that the latest relevant report can be found in sampled records.', 5=>'Recognise this as a reported strength and maintain periodic review. Check that the latest relevant report can be found in sampled records.'],
],
'A5'=>[
'id'=>'A5',
'domain'=>'A',
'question'=>'How consistently do you check that files used during the day have been returned to their correct place?',
'title'=>'Return files to the correct place',
'consequence'=>'Files left out or misplaced may be unavailable at the next visit.',
'role'=>'Receptionist or clinic owner',
'timing'=>'Within 14 days',
'completion_check'=>'Compare files taken out against files returned.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Compare files taken out against files returned.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Assign an end-of-day check for files taken out during the day. Establish the routine and identify who will carry it out.', 2=>'Assign an end-of-day check for files taken out during the day. Make the steps consistent and assign responsibility.', 3=>'Assign an end-of-day check for files taken out during the day. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Compare files taken out against files returned.', 5=>'Recognise this as a reported strength and maintain periodic review. Compare files taken out against files returned.'],
],
'B1'=>[
'id'=>'B1',
'domain'=>'B',
'question'=>'How consistently is the patient\'s treatment goal written clearly enough to review at a later visit?',
'title'=>'Record a clear treatment goal',
'consequence'=>'An unclear recorded goal may make later review harder.',
'role'=>'Treating doctor',
'timing'=>'Within 14 days',
'completion_check'=>'Check sampled treatment episodes for a documented goal.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Check sampled treatment episodes for a documented goal.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Include a clear treatment goal in the treatment record. Establish the routine and identify who will carry it out.', 2=>'Include a clear treatment goal in the treatment record. Make the steps consistent and assign responsibility.', 3=>'Include a clear treatment goal in the treatment record. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Check sampled treatment episodes for a documented goal.', 5=>'Recognise this as a reported strength and maintain periodic review. Check sampled treatment episodes for a documented goal.'],
],
'B2'=>[
'id'=>'B2',
'domain'=>'B',
'question'=>'How consistently are treatment notes completed before the patient\'s visit is considered finished?',
'title'=>'Finish notes before closing the visit',
'consequence'=>'Unfinished notes may leave the visit record incomplete.',
'role'=>'Treating doctor',
'timing'=>'Within 7 days',
'completion_check'=>'Check sampled completed visits for dated notes.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Check sampled completed visits for dated notes.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Add note completion to the end-of-visit routine. Establish the routine and identify who will carry it out.', 2=>'Add note completion to the end-of-visit routine. Make the steps consistent and assign responsibility.', 3=>'Add note completion to the end-of-visit routine. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Check sampled completed visits for dated notes.', 5=>'Recognise this as a reported strength and maintain periodic review. Check sampled completed visits for dated notes.'],
],
'B3'=>[
'id'=>'B3',
'domain'=>'B',
'question'=>'How reliably can another treating doctor understand what was done at the previous visit from the written record alone?',
'title'=>'Make written notes useful for handover',
'consequence'=>'Incomplete written detail may make another doctor depend on verbal explanation.',
'role'=>'Treating doctor and authorised colleague',
'timing'=>'Within 14 days',
'completion_check'=>'Ask another authorised treating doctor to review a sample record.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Ask another authorised treating doctor to review a sample record.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Use a consistent session-note format with enough detail for handover. Establish the routine and identify who will carry it out.', 2=>'Use a consistent session-note format with enough detail for handover. Make the steps consistent and assign responsibility.', 3=>'Use a consistent session-note format with enough detail for handover. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Ask another authorised treating doctor to review a sample record.', 5=>'Recognise this as a reported strength and maintain periodic review. Ask another authorised treating doctor to review a sample record.'],
],
'B4'=>[
'id'=>'B4',
'domain'=>'B',
'question'=>'How consistently are changes to the patient\'s exercises or treatment recorded so the next visit follows the updated plan?',
'title'=>'Record treatment and exercise changes',
'consequence'=>'Unrecorded changes may leave the next visit without the updated plan.',
'role'=>'Treating doctor',
'timing'=>'Within 14 days',
'completion_check'=>'Check sampled changes against the following visit\'s record.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Check sampled changes against the following visit\'s record.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Record dated changes in the patient\'s treatment record. Establish the routine and identify who will carry it out.', 2=>'Record dated changes in the patient\'s treatment record. Make the steps consistent and assign responsibility.', 3=>'Record dated changes in the patient\'s treatment record. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Check sampled changes against the following visit\'s record.', 5=>'Recognise this as a reported strength and maintain periodic review. Check sampled changes against the following visit\'s record.'],
],
'B5'=>[
'id'=>'B5',
'domain'=>'B',
'question'=>'How consistently is the patient\'s progress reviewed against the treatment goal at the review point chosen by the treating doctor?',
'title'=>'Review progress at the chosen point',
'consequence'=>'A missing progress review may leave the record unclear about progress against the goal.',
'role'=>'Treating doctor',
'timing'=>'Within 14 days',
'completion_check'=>'Check episodes whose chosen review point has been reached.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Check episodes whose chosen review point has been reached.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Record the doctor\'s chosen review point and document the progress review. Establish the routine and identify who will carry it out.', 2=>'Record the doctor\'s chosen review point and document the progress review. Make the steps consistent and assign responsibility.', 3=>'Record the doctor\'s chosen review point and document the progress review. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Check episodes whose chosen review point has been reached.', 5=>'Recognise this as a reported strength and maintain periodic review. Check episodes whose chosen review point has been reached.'],
],
'C1'=>[
'id'=>'C1',
'domain'=>'C',
'question'=>'How consistently do you check that every visit requiring payment has a charge recorded?',
'title'=>'Check charges for payable visits',
'consequence'=>'Missing recorded charges may leave the patient ledger incomplete.',
'role'=>'Receptionist and clinic owner',
'timing'=>'Within 7 days',
'completion_check'=>'Check a sample of chargeable visits for missing charges.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Check a sample of chargeable visits for missing charges.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>true,
'recommendations'=>[1=>'Compare chargeable visits against recorded charges. Establish the routine and identify who will carry it out.', 2=>'Compare chargeable visits against recorded charges. Make the steps consistent and assign responsibility.', 3=>'Compare chargeable visits against recorded charges. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Check a sample of chargeable visits for missing charges.', 5=>'Recognise this as a reported strength and maintain periodic review. Check a sample of chargeable visits for missing charges.'],
],
'C2'=>[
'id'=>'C2',
'domain'=>'C',
'question'=>'How consistently are payments entered into the patient\'s payment record on the day they are received?',
'title'=>'Enter payments on the receipt day',
'consequence'=>'Delayed payment entries may leave pending amounts unclear.',
'role'=>'Receptionist',
'timing'=>'Within 7 days',
'completion_check'=>'Compare payment dates and patient payment entries.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Compare payment dates and patient payment entries.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>true,
'recommendations'=>[1=>'Assign same-day payment recording against the correct patient. Establish the routine and identify who will carry it out.', 2=>'Assign same-day payment recording against the correct patient. Make the steps consistent and assign responsibility.', 3=>'Assign same-day payment recording against the correct patient. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Compare payment dates and patient payment entries.', 5=>'Recognise this as a reported strength and maintain periodic review. Compare payment dates and patient payment entries.'],
],
'C3'=>[
'id'=>'C3',
'domain'=>'C',
'question'=>'How reliably can staff explain a patient\'s pending amount using the payment record, without relying on memory?',
'title'=>'Explain pending amounts from the record',
'consequence'=>'Reliance on memory may make payment explanations inconsistent.',
'role'=>'Receptionist',
'timing'=>'Within 14 days',
'completion_check'=>'Trace a sample of balances back to charges and payments.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Trace a sample of balances back to charges and payments.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Maintain one patient ledger with charges, payments and balance. Establish the routine and identify who will carry it out.', 2=>'Maintain one patient ledger with charges, payments and balance. Make the steps consistent and assign responsibility.', 3=>'Maintain one patient ledger with charges, payments and balance. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Trace a sample of balances back to charges and payments.', 5=>'Recognise this as a reported strength and maintain periodic review. Trace a sample of balances back to charges and payments.'],
],
'C4'=>[
'id'=>'C4',
'domain'=>'C',
'question'=>'How consistently do you compare the day\'s recorded payments with the money actually received?',
'title'=>'Compare daily payments with collections',
'consequence'=>'Differences between the day\'s entries and actual collections may go unnoticed.',
'role'=>'Clinic owner or nominated accounts person',
'timing'=>'Within 7 days',
'completion_check'=>'Keep a daily reconciliation record and resolve differences.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Keep a daily reconciliation record and resolve differences.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>true,
'recommendations'=>[1=>'Introduce an end-of-day reconciliation across payment methods. Establish the routine and identify who will carry it out.', 2=>'Introduce an end-of-day reconciliation across payment methods. Make the steps consistent and assign responsibility.', 3=>'Introduce an end-of-day reconciliation across payment methods. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Keep a daily reconciliation record and resolve differences.', 5=>'Recognise this as a reported strength and maintain periodic review. Keep a daily reconciliation record and resolve differences.'],
],
'C5'=>[
'id'=>'C5',
'domain'=>'C',
'question'=>'How consistently do you review pending patient payments on a fixed day each week?',
'title'=>'Review pending payments weekly',
'consequence'=>'Pending payments may remain unresolved without a fixed review routine.',
'role'=>'Receptionist and clinic owner',
'timing'=>'Within 7 days',
'completion_check'=>'Keep a dated review record with follow-up actions.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Keep a dated review record with follow-up actions.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Assign a fixed weekly pending-payment review. Establish the routine and identify who will carry it out.', 2=>'Assign a fixed weekly pending-payment review. Make the steps consistent and assign responsibility.', 3=>'Assign a fixed weekly pending-payment review. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Keep a dated review record with follow-up actions.', 5=>'Recognise this as a reported strength and maintain periodic review. Keep a dated review record with follow-up actions.'],
],
'D1'=>[
'id'=>'D1',
'domain'=>'D',
'question'=>'How consistently is one person clearly responsible for checking that the day\'s patient records are complete?',
'title'=>'Check daily record completeness',
'consequence'=>'Without a clear checker, missing record details may remain unnoticed.',
'role'=>'Clinic owner or nominated records checker',
'timing'=>'Within 7 days',
'completion_check'=>'Record who checked the day\'s records and any gaps found.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Record who checked the day\'s records and any gaps found.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Assign a named role for the daily completeness check. Establish the routine and identify who will carry it out.', 2=>'Assign a named role for the daily completeness check. Make the steps consistent and assign responsibility.', 3=>'Assign a named role for the daily completeness check. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Record who checked the day\'s records and any gaps found.', 5=>'Recognise this as a reported strength and maintain periodic review. Record who checked the day\'s records and any gaps found.'],
],
'D2'=>[
'id'=>'D2',
'domain'=>'D',
'question'=>'How reliably can routine reception work continue when the usual receptionist or assistant is absent?',
'title'=>'Cover routine reception work',
'consequence'=>'Reception tasks may be interrupted when the usual person is absent.',
'role'=>'Receptionist and nominated backup',
'timing'=>'Within 14 days',
'completion_check'=>'Run a supervised handover or absence-cover check.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Run a supervised handover or absence-cover check.',
'na_review'=>'Confirm whether the clinic has a reception function. If none exists, record that reason and review applicability; do not assume a reception backup is required.',
'control'=>false,
'recommendations'=>[1=>'Document the reception routine and train a backup person. Establish the routine and identify who will carry it out.', 2=>'Document the reception routine and train a backup person. Make the steps consistent and assign responsibility.', 3=>'Document the reception routine and train a backup person. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Run a supervised handover or absence-cover check.', 5=>'Recognise this as a reported strength and maintain periodic review. Run a supervised handover or absence-cover check.'],
],
'D3'=>[
'id'=>'D3',
'domain'=>'D',
'question'=>'How consistently do you review patients who stopped attending before their planned treatment was completed?',
'title'=>'Review unexpected discontinuation',
'consequence'=>'Unexpected discontinuation may remain unnoticed without a review list.',
'role'=>'Treating doctor',
'timing'=>'Within 14 days',
'completion_check'=>'Record which cases were reviewed and the next step chosen.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Record which cases were reviewed and the next step chosen.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Maintain a review list for unexpected treatment discontinuation. Establish the routine and identify who will carry it out.', 2=>'Maintain a review list for unexpected treatment discontinuation. Make the steps consistent and assign responsibility.', 3=>'Maintain a review list for unexpected treatment discontinuation. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Record which cases were reviewed and the next step chosen.', 5=>'Recognise this as a reported strength and maintain periodic review. Record which cases were reviewed and the next step chosen.'],
],
'D4'=>[
'id'=>'D4',
'domain'=>'D',
'question'=>'How reliably can you obtain an accurate weekly count of completed treatment visits without counting individual entries yourself?',
'title'=>'Check the weekly completed-visit count',
'consequence'=>'Unclear counting rules may produce inconsistent weekly summaries.',
'role'=>'Receptionist and clinic owner',
'timing'=>'Within 14 days',
'completion_check'=>'Compare the weekly total with the underlying visit records.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Compare the weekly total with the underlying visit records.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>false,
'recommendations'=>[1=>'Maintain a weekly summary with a defined completed-visit rule. Establish the routine and identify who will carry it out.', 2=>'Maintain a weekly summary with a defined completed-visit rule. Make the steps consistent and assign responsibility.', 3=>'Maintain a weekly summary with a defined completed-visit rule. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Compare the weekly total with the underlying visit records.', 5=>'Recognise this as a reported strength and maintain periodic review. Compare the weekly total with the underlying visit records.'],
],
'D5'=>[
'id'=>'D5',
'domain'=>'D',
'question'=>'How consistently do you check that a clinic problem identified earlier has actually been corrected?',
'title'=>'Confirm that clinic problems are corrected',
'consequence'=>'A problem marked complete without checking may recur or remain unresolved.',
'role'=>'Clinic owner',
'timing'=>'Within 7 days',
'completion_check'=>'Check completed corrective actions against the original issue.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Check completed corrective actions against the original issue.',
'na_review'=>'Confirm why checking that an earlier clinic problem has actually been corrected is considered inapplicable. Record and review the reason; do not assume corrective-action review is unnecessary.',
'control'=>false,
'recommendations'=>[1=>'Maintain an issue list with responsibility and a follow-up date. Establish the routine and identify who will carry it out.', 2=>'Maintain an issue list with responsibility and a follow-up date. Make the steps consistent and assign responsibility.', 3=>'Maintain an issue list with responsibility and a follow-up date. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Check completed corrective actions against the original issue.', 5=>'Recognise this as a reported strength and maintain periodic review. Check completed corrective actions against the original issue.'],
],
'E1'=>[
'id'=>'E1',
'domain'=>'E',
'question'=>'How consistently are patient files kept where visitors and other patients cannot read them?',
'title'=>'Keep records away from public viewing',
'consequence'=>'Exposed files or screens may allow visitors to read patient information.',
'role'=>'Clinic owner and all staff',
'timing'=>'Within 7 days',
'completion_check'=>'Walk through public areas and check for exposed patient information.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Walk through public areas and check for exposed patient information.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>true,
'recommendations'=>[1=>'Keep paper records secure and digital records away from public view. Establish the routine and identify who will carry it out.', 2=>'Keep paper records secure and digital records away from public view. Make the steps consistent and assign responsibility.', 3=>'Keep paper records secure and digital records away from public view. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Walk through public areas and check for exposed patient information.', 5=>'Recognise this as a reported strength and maintain periodic review. Walk through public areas and check for exposed patient information.'],
],
'E2'=>[
'id'=>'E2',
'domain'=>'E',
'question'=>'How consistently do you check that only the appropriate staff can access patient records?',
'title'=>'Check appropriate staff access',
'consequence'=>'Unchecked access routes may expose records beyond staff responsibilities.',
'role'=>'Clinic owner',
'timing'=>'Within 7 days',
'completion_check'=>'Review current users, keys and other access routes.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Review current users, keys and other access routes.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>true,
'recommendations'=>[1=>'Review access according to each person\'s responsibilities. Establish the routine and identify who will carry it out.', 2=>'Review access according to each person\'s responsibilities. Make the steps consistent and assign responsibility.', 3=>'Review access according to each person\'s responsibilities. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Review current users, keys and other access routes.', 5=>'Recognise this as a reported strength and maintain periodic review. Review current users, keys and other access routes.'],
],
'E3'=>[
'id'=>'E3',
'domain'=>'E',
'question'=>'How reliably do you keep a separate, protected copy of important records in case the originals are lost or damaged?',
'title'=>'Keep a separate protected record copy',
'consequence'=>'Loss or damage to originals may leave records unavailable without a protected copy.',
'role'=>'Clinic owner and nominated support person',
'timing'=>'Within 7 days',
'completion_check'=>'Check that the copy is current and accessible to authorised staff.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Check that the copy is current and accessible to authorised staff.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>true,
'recommendations'=>[1=>'Maintain a separate protected recovery copy of essential records. Establish the routine and identify who will carry it out.', 2=>'Maintain a separate protected recovery copy of essential records. Make the steps consistent and assign responsibility.', 3=>'Maintain a separate protected recovery copy of essential records. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Check that the copy is current and accessible to authorised staff.', 5=>'Recognise this as a reported strength and maintain periodic review. Check that the copy is current and accessible to authorised staff.'],
],
'E4'=>[
'id'=>'E4',
'domain'=>'E',
'question'=>'How confidently can you recover a sample patient record from that separate copy, based on a check you have actually performed?',
'title'=>'Check sample record recovery',
'consequence'=>'An untested copy may not provide usable records when needed.',
'role'=>'Clinic owner and nominated support person',
'timing'=>'Within 7 days',
'completion_check'=>'Record the recovery date, result and any gaps found.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Record the recovery date, result and any gaps found.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>true,
'recommendations'=>[1=>'Perform and document a controlled sample recovery check. Establish the routine and identify who will carry it out.', 2=>'Perform and document a controlled sample recovery check. Make the steps consistent and assign responsibility.', 3=>'Perform and document a controlled sample recovery check. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Record the recovery date, result and any gaps found.', 5=>'Recognise this as a reported strength and maintain periodic review. Record the recovery date, result and any gaps found.'],
],
'E5'=>[
'id'=>'E5',
'domain'=>'E',
'question'=>'How consistently do you check that a person leaving the clinic has returned clinic records and no longer has access to them?',
'title'=>'Check returned records and remove access',
'consequence'=>'Departed staff may retain clinic records or access without an exit check.',
'role'=>'Clinic owner',
'timing'=>'Within 7 days',
'completion_check'=>'Review the most recent departure or test the checklist if none occurred.',
'verification'=>'Ask the responsible person to explain the current routine and show an anonymised example. Review the most recent departure or test the checklist if none occurred.',
'na_review'=>'Confirm why this process is considered inapplicable, record the reason and review that decision before excluding it.',
'control'=>true,
'recommendations'=>[1=>'Use a staff-exit checklist for records, keys and digital access. Establish the routine and identify who will carry it out.', 2=>'Use a staff-exit checklist for records, keys and digital access. Make the steps consistent and assign responsibility.', 3=>'Use a staff-exit checklist for records, keys and digital access. Add a completion check and record how exceptions are addressed.', 4=>'Maintain the checks for this process and review recurring gaps. Review the most recent departure or test the checklist if none occurred.', 5=>'Recognise this as a reported strength and maintain periodic review. Review the most recent departure or test the checklist if none occurred.'],
],
]];
$catalogue['measurement_catalogue']=require __DIR__.'/roadmap-catalogue.php';
return $catalogue;
